
import React, { Fragment } from 'react'

import { useTranslation } from 'react-i18next';
import { Grid, Typography, Divider } from '@material-ui/core';
import { Link } from 'react-router-dom';
import logoblue from '../../assets/logored.png'



function Gdpr() {
  const [t] = useTranslation("global");
 
  return (

    <Fragment>
        <Link to="/">
            <img className="logo" src={logoblue} alt="" />
          </Link>
          <Divider></Divider>

          <Grid style={{padding:"2rem"}} maxWidth="xs">
            <Typography style={{marginBottom:"3rem"}} align="center" 
             variant="h4">Privacy Policy for gomoving</Typography>

            <Typography variant="h4"> Privacy Policy</Typography>
            <Typography>This Privacy Policy describes Our policies and procedures on the collection, 
                use and disclosure of Your information when You use the Service and tells 
                You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. 
By using the Service, You agree to the collection 
and use of information in accordance with this Privacy Policy. This Privacy Policy 
has been created with the help of the Privacy Policy Generator.
</Typography>

<Typography variant="h4"> Interpretation</Typography>
<Typography>The words of which the initial letter is capitalized have meanings defined under
     the following conditions. The following definitions shall have
     the same meaning regardless of whether they appear in singular or in plural.
</Typography>

<Typography variant="h4"> Definitions</Typography>
<Typography>For the purposes of this Privacy Policy:

Account means a unique account created for You to access our Service or parts of our Service.

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to gomoving.

Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.

Country refers to: Spain

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

Personal Data is any information that relates to an identified or identifiable individual.

Service refers to the Website.

Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

Website refers to gomoving, accessible from http://www.gomoving.com

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
</Typography>

<Typography variant="h4"> Contact Us</Typography>
<Typography>If you have any questions about this Privacy Policy, You can contact us:

By email: office@mycompany.com
</Typography>
  
           
   
            </Grid>
       
    </Fragment>
    

  );
}

export default Gdpr;